call plug#begin('~/.vim/plugged')
    Plug 'tomasr/molokai'
    Plug 'vim-airline/vim-airline'
    Plug 'tpope/vim-fugitive'
    Plug 'kien/ctrlp.vim'
    Plug 'preservim/nerdtree'
    Plug 'airblade/vim-gitgutter'
    Plug 'vim-syntastic/syntastic'
    Plug 'python-mode/python-mode', { 'for': 'python', 'branch': 'last-py2-support' }
call plug#end()

syntax enable
colorscheme molokai
let g:pymode = 1
let g:pymode_rope = 1
set completeopt=menuone,noinsert
let g:pymode_rope_completion = 1
let g:pymode_rope_autoimport = 0
let g:pymode_rope_goto_definition_bind = '<C-c>g'


